### ISSUE TITLE
Disable create user

### ISSUE THREAD

**Issue by Morgok857** [bchanudet/verdaccio-mysql#3]
I implemented Verdaccio with MYSQL authentication and it is working fine.

I can't find any option to disable the creation of new users as with the htpasswd authentication method which has the option 'max_users:'

Is it possible to configure any parameter to disable user creation with 'npm adduser' command?

**Comment by bchanudet** [comment]
Hi @Morgok857, 

Allow me to quote the readme: 
> Declare `add_user`  as an empty string to forbid anyone to create a new user in the database from Verdaccio or the npm CLI.

So, if your configuration file looks like this (some parts were removed for brevity) :
```yaml
# auth:
  mysql:
    queries:
      add_user: ""
      update_user: "UPDATE `users` [...]"
      auth_user: "SELECT [...]"
```

That should be enough to prevent new users to be added to the database. The plugin may warn you in the verdaccio logs that the query is empty, but it still works smoothly. Users that are already in the database will still be able to log in as expected.

**But this is not an equivalent to the `max_users` option of the htpasswd plugin**. But we can emulate the same thing, by using an insert trigger on the mysql database, for example:

```sql
DELIMITER $$

CREATE TRIGGER trigger_check_max_users
BEFORE INSERT ON `users`
FOR EACH ROW
BEGIN
  IF 
    (SELECT count(*) FROM `users`) >= 10 -- set here the max_users value you want
  THEN
   SIGNAL SQLSTATE '02000' SET MESSAGE_TEXT = 'Warning: There are already too many users.';
END IF;

END$$

DELIMITER ;
``` 

Such a trigger will cause the insert query for the 11th users to fail, and thus will not be added to the database.

Hope this helps,

**Comment by Morgok857** [comment]
HI @bchanudet 

Excellent!!

It is the same temporary solution that I thought, but it is not the best solution since it will leave many errors in the application logs.

I understand that this feature does not exist for this plugin for now and we implement a workaround.

Then I'm going to go for the alternative you mention.

Thanks
